# Generated by Django 4.1.7 on 2023-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pimg',
            field=models.ImageField(default='defaultpic.png', upload_to='displaypic', verbose_name='pimg'),
        ),
    ]
