# Generated by Django 4.1.7 on 2023-03-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_booking_bokked_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bokked_d',
            field=models.DateTimeField(null=True, verbose_name='booked_d'),
        ),
    ]
